//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiToothPaste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class toothpaste
    {
        public int id_toothpaste { get; set; }
        public string name_toothpaste { get; set; }
        public int abrasiveness_index { get; set; }
        public string country_of_origin { get; set; }
        public int volume { get; set; }
        public double price { get; set; }
        public string Image { get; set; }
    }
}
